### ISSUE TITLE
ConnectTimeoutError

### ISSUE THREAD

**Issue by predmijat** [tastyminerals/afreeca-bw#3]
This worked for me, then I didn't watch it for a month or so and when I tried it yesterday, got an error:
```
Play stream: error: Unable to open URL: http://sessionmanager01.afreeca.tv:6060/broad_stream_assign.html (HTTPConnectionPool(host='sessionmanager01.afreeca.tv', port=6060): Max retries exceeded with url: /broad_stream_assign.html?return_type=gs_cdn&use_cors=true&cors_origin_url=m.afreeca.com&broad_no=196708366-mobile-hd-rtmp&broad_key=196708366-flash-hd-rtmp (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb789c16860>, 'Connection to sessionmanager01.afreeca.tv timed out. (connect timeout=20.0)')))
```
Did a `git pull`, followed steps again, same error...what's up?

**Comment by tastyminerals** [comment]
Nothing I can do, afreeca keeps changing its API and I am too busy to keep it updated all the time :(
Keep watching [this thread](http://www.teamliquid.net/forum/brood-war/512913-guide-watch-afreeca-sc-bw-streams-with-vlc?page=22). I will update the script as soon as somebody fixes afreecatv.py

**Comment by predmijat** [comment]
That's ok :)
